spring.application.name=budgie-backend
spring.config.import=classpath:frontend-paths.properties
spring.messages.basename=messages

spring.datasource.url=${DATASOURCE_URL:jdbc:mysql://localhost:3306/budgie_database}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.password=${DATASOURCE_PASSWORD}
api.security.token.secret=${TOKEN_SECRET}
spring.mail.password=${MAIL_PASSWORD}

# Criação da Tabela
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE}
