spring.application.name=budgie-backend
spring.config.import=classpath:application-secrets.properties

spring.datasource.url=jdbc:postgresql://localhost:5432/budgie_database
spring.datasource.username=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Criação da Tabela
spring.jpa.hibernate.ddl-auto=update